adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/MobileNet_for_mobile0.5.tflite /data/local/tmp
adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/MobileNet_for_mobile0.625.tflite /data/local/tmp
adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/MobileNet_for_mobile0.75.tflite /data/local/tmp
adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/MobileNet_for_mobile0.875.tflite /data/local/tmp
adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/MobileNet_for_mobile1.0.tflite /data/local/tmp
adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/VGG19_for_mobile0.5.tflite /data/local/tmp
adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/VGG19_for_mobile0.625.tflite /data/local/tmp
adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/VGG19_for_mobile0.75.tflite /data/local/tmp
adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/VGG19_for_mobile0.875.tflite /data/local/tmp
adb push /mnt/additional/nitthilan/data/ml_tutorial/imagenet/VGG19_for_mobile1.0.tflite /data/local/tmp
