adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_svhn_2.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_svhn_2.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_svhn_3.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_svhn_3.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_svhn_4.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_mnist_2.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_mnist_2.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_mnist_3.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_mnist_3.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_mnist_4.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_cifar10_2.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_cifar10_2.25.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_cifar10_2.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_cifar10_3.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_cifar10_3.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_conv_cifar10_4.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_svhn_2.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_svhn_2.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_svhn_3.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_svhn_3.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_svhn_4.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_mnist_2.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_mnist_2.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_mnist_3.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_mnist_3.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_mnist_4.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_cifar10_2.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_cifar10_2.25.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_cifar10_2.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_cifar10_3.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_cifar10_3.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_vgg_cifar10_4.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_svhn_2.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_svhn_2.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_svhn_3.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_svhn_3.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_svhn_4.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_mnist_2.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_mnist_2.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_mnist_3.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_mnist_3.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_mnist_4.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_cifar10_2.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_cifar10_2.25.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_cifar10_2.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_cifar10_3.0.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_cifar10_3.5.h5 /data/local/tmp
adb push /mnt/additional/nitthilan/ml_tutorials/conv/vert_filt_models/vert_filt_MobileNet_for_mobile_cifar10_4.0.h5 /data/local/tmp